### ISSUE TITLE
Impossible to delete team

### ISSUE THREAD

**Issue by M4rissa** [AreaFiftyLAN/lancie-api#227]
Would be nice if you could leave the team even as a last member or just have the option to delete it.

**Comment by skamoen** [comment]
Hi M4rissa,
Thanks for submitting an issue! It is intentional that users can not delete Teams. However it does make sense that the last member of a team should be able to remove it. We'll definitely come up with a solution of that for next year. In the meantime, if you want a team removed, you can send us an email or request it on Discord!
